"use client";

import type { CalendarDay, TimelineStats } from "@taghvim/types/calendar";
import { TimelineView } from "@taghvim/components/TimelineView";

const DEMO_DAYS: CalendarDay[] = [
  {
    id: 1,
    date: "2026-07-04",
    title: "آغاز موج جدید تهدیدات",
    summary:
      "ثبت نخستین نشانه‌های افزایش فعالیت دشمن در مرزهای غربی و فضای سایبری.",
    status: "published",
    is_featured: false,
    enemy_actions_count: 2,
    government_actions_count: 2,
    activity_score: 6,
    enemy_actions: [
      {
        id: 1,
        title: "شناسایی پهپادهای ناشناس در غرب کشور",
        description: "رصد و تحلیل این اقدام در سامانه ثبت شده است.",
        severity: "high",
        source: "مرکز رصد",
        location: "مرز غربی",
        occurred_at: null,
        status: "published",
      },
      {
        id: 2,
        title: "تلاش برای نفوذ به زیرساخت ارتباطی",
        description: "تلاش برای دسترسی غیرمجاز شناسایی و مسدود شد.",
        severity: "medium",
        source: "مرکز رصد",
        location: null,
        occurred_at: null,
        status: "published",
      },
    ],
    government_actions: [
      {
        id: 1,
        title: "افزایش آماده‌باش پدافند هوایی",
        description: "آماده‌باش کامل سامانه‌های پدافندی.",
        agency: "نیروی پدافند هوایی",
        completed_at: null,
        status: "published",
        response_to_id: 1,
      },
      {
        id: 2,
        title: "فعال‌سازی مرکز پایش سایبری",
        description: "پایش ۲۴ ساعته زیرساخت‌های حیاتی.",
        agency: "مرکز ملی فضای مجازی",
        completed_at: null,
        status: "published",
        response_to_id: 2,
      },
    ],
  },
  {
    id: 2,
    date: "2026-07-05",
    title: "اوج حملات پهپادی",
    summary: "روز پرتنش با چندین اقدام خصمانه و پاسخ سریع نیروهای دفاعی.",
    status: "published",
    is_featured: true,
    enemy_actions_count: 4,
    government_actions_count: 3,
    activity_score: 11,
    enemy_actions: [
      {
        id: 3,
        title: "حمله پهپادی به تأسیسات مرزی",
        description: "چندین هدف همزمان مورد تهدید قرار گرفت.",
        severity: "critical",
        source: "مرکز رصد",
        location: "غرب کشور",
        occurred_at: null,
        status: "published",
      },
      {
        id: 4,
        title: "انتشار اخبار جعلی در شبکه‌های اجتماعی",
        description: "کمپین سیاه‌نمایی سازمان‌یافته.",
        severity: "medium",
        source: "مرکز رصد",
        location: null,
        occurred_at: null,
        status: "published",
      },
      {
        id: 5,
        title: "اختلال موقت در سرویس‌های بانکی",
        description: "حمله سایبری محدود و کنترل‌شده.",
        severity: "high",
        source: "مرکز رصد",
        location: null,
        occurred_at: null,
        status: "published",
      },
      {
        id: 6,
        title: "تهدید جدید تحریم‌های هدفمند",
        description: "فشار اقتصادی و دیپلماتیک.",
        severity: "medium",
        source: "مرکز رصد",
        location: null,
        occurred_at: null,
        status: "published",
      },
    ],
    government_actions: [
      {
        id: 3,
        title: "سرنگونی پهپادهای مهاجم",
        description: "پاسخ عملیاتی موفق پدافند.",
        agency: "نیروی هوافضا",
        completed_at: null,
        status: "published",
        response_to_id: 3,
      },
      {
        id: 4,
        title: "خنثی‌سازی حمله سایبری بانکی",
        description: "بازیابی سریع سرویس‌ها.",
        agency: "پلیس فتا",
        completed_at: null,
        status: "published",
        response_to_id: 5,
      },
      {
        id: 5,
        title: "اطلاع‌رسانی رسمی و شفاف‌سازی",
        description: "بیانیه رسمی برای افکار عمومی.",
        agency: "وزارت امور خارجه",
        completed_at: null,
        status: "published",
        response_to_id: 4,
      },
    ],
  },
  {
    id: 3,
    date: "2026-07-06",
    title: "تثبیت وضعیت و بازسازی",
    summary: "کاهش نسبی تهدیدات و تمرکز بر بازسازی زیرساخت‌ها.",
    status: "published",
    is_featured: false,
    enemy_actions_count: 1,
    government_actions_count: 3,
    activity_score: 5,
    enemy_actions: [
      {
        id: 7,
        title: "ادامه فشار رسانه‌ای خارجی",
        description: "ادامه روایت‌سازی خصمانه.",
        severity: "low",
        source: "مرکز رصد",
        location: null,
        occurred_at: null,
        status: "published",
      },
    ],
    government_actions: [
      {
        id: 6,
        title: "بازدید میدانی از مناطق آسیب‌دیده",
        description: "حمایت میدانی و ارزیابی خسارت.",
        agency: "ستاد بحران",
        completed_at: null,
        status: "published",
        response_to_id: null,
      },
      {
        id: 7,
        title: "تقویت سامانه‌های پدافندی",
        description: "استقرار تجهیزات تکمیلی.",
        agency: "نیروی پدافند هوایی",
        completed_at: null,
        status: "published",
        response_to_id: null,
      },
      {
        id: 8,
        title: "هماهنگی دیپلماتیک با شرکای منطقه‌ای",
        description: "تبادل اطلاعات و هماهنگی امنیتی.",
        agency: "وزارت امور خارجه",
        completed_at: null,
        status: "published",
        response_to_id: null,
      },
    ],
  },
  {
    id: 4,
    date: "2026-07-07",
    title: "رصد مستمر و آمادگی",
    summary: "وضعیت پایدار با پایش مداوم و آمادگی عملیاتی.",
    status: "published",
    is_featured: false,
    enemy_actions_count: 2,
    government_actions_count: 2,
    activity_score: 6,
    enemy_actions: [
      {
        id: 8,
        title: "حرکت مشکوک شناورهای ناشناس",
        description: "رصد دریایی در خلیج فارس.",
        severity: "medium",
        source: "مرکز رصد",
        location: "خلیج فارس",
        occurred_at: null,
        status: "published",
      },
      {
        id: 9,
        title: "اسکن پورت‌های حساس دولتی",
        description: "تلاش شناسایی آسیب‌پذیری.",
        severity: "low",
        source: "مرکز رصد",
        location: null,
        occurred_at: null,
        status: "published",
      },
    ],
    government_actions: [
      {
        id: 9,
        title: "گشت دریایی تقویت‌شده",
        description: "افزایش حضور عملیاتی.",
        agency: "نیروی دریایی",
        completed_at: null,
        status: "published",
        response_to_id: 8,
      },
      {
        id: 10,
        title: "به‌روزرسانی دیوار آتش ملی",
        description: "سخت‌سازی زیرساخت‌ها.",
        agency: "مرکز ملی فضای مجازی",
        completed_at: null,
        status: "published",
        response_to_id: 9,
      },
    ],
  },
  {
    id: 5,
    date: "2026-07-08",
    title: "روز آرام با پایش فعال",
    summary: "فعالیت دشمن در سطح پایین؛ تمرکز بر آمادگی.",
    status: "published",
    is_featured: false,
    enemy_actions_count: 1,
    government_actions_count: 1,
    activity_score: 3,
    enemy_actions: [
      {
        id: 10,
        title: "شایعات جدید در فضای مجازی",
        description: "پایش و رصد شایعات.",
        severity: "low",
        source: "مرکز رصد",
        location: null,
        occurred_at: null,
        status: "published",
      },
    ],
    government_actions: [
      {
        id: 11,
        title: "برگزاری رزمایش دفاع شهری",
        description: "افزایش آمادگی مردمی.",
        agency: "سازمان پدافند غیرعامل",
        completed_at: null,
        status: "published",
        response_to_id: null,
      },
    ],
  },
  {
    id: 6,
    date: "2026-07-09",
    title: "موج دوم فشار ترکیبی",
    summary: "ترکیب تهدید سایبری، رسانه‌ای و نظامی در یک روز.",
    status: "published",
    is_featured: true,
    enemy_actions_count: 3,
    government_actions_count: 4,
    activity_score: 10,
    enemy_actions: [
      {
        id: 11,
        title: "حمله DDoS به پورتال‌های دولتی",
        description: "حجم بالای ترافیک مخرب.",
        severity: "high",
        source: "مرکز رصد",
        location: null,
        occurred_at: null,
        status: "published",
      },
      {
        id: 12,
        title: "پهپادهای شناسایی در جنوب",
        description: "نفوذ هوایی محدود.",
        severity: "high",
        source: "مرکز رصد",
        location: "جنوب کشور",
        occurred_at: null,
        status: "published",
      },
      {
        id: 13,
        title: "کمپین سیاه‌نمایی بین‌المللی",
        description: "عملیات شناختی.",
        severity: "medium",
        source: "مرکز رصد",
        location: null,
        occurred_at: null,
        status: "published",
      },
    ],
    government_actions: [
      {
        id: 12,
        title: "مقابله با حمله DDoS",
        description: "پایداری سرویس‌ها حفظ شد.",
        agency: "پلیس فتا",
        completed_at: null,
        status: "published",
        response_to_id: 11,
      },
      {
        id: 13,
        title: "رهگیری و انهدام پهپاد شناسایی",
        description: "پاسخ سریع پدافند.",
        agency: "نیروی هوافضا",
        completed_at: null,
        status: "published",
        response_to_id: 12,
      },
      {
        id: 14,
        title: "انتشار گزارش مستند برای افکار عمومی",
        description: "شفاف‌سازی رویدادها.",
        agency: "شورای عالی امنیت ملی",
        completed_at: null,
        status: "published",
        response_to_id: 13,
      },
      {
        id: 15,
        title: "بیانیه دیپلماتیک رسمی",
        description: "موضع‌گیری رسمی.",
        agency: "وزارت امور خارجه",
        completed_at: null,
        status: "published",
        response_to_id: null,
      },
    ],
  },
  {
    id: 7,
    date: "2026-07-10",
    title: "جمع‌بندی هفته اول",
    summary: "مرور اقدامات هفته و آماده‌سازی برای مرحله بعد.",
    status: "published",
    is_featured: false,
    enemy_actions_count: 1,
    government_actions_count: 2,
    activity_score: 4,
    enemy_actions: [
      {
        id: 14,
        title: "کاهش محسوس فعالیت میدانی دشمن",
        description: "کاهش نسبی تهدیدات میدانی.",
        severity: "low",
        source: "مرکز رصد",
        location: null,
        occurred_at: null,
        status: "published",
      },
    ],
    government_actions: [
      {
        id: 16,
        title: "گزارش هفتگی به مردم",
        description: "خلاصه عملکرد هفته.",
        agency: "سخنگوی دولت",
        completed_at: null,
        status: "published",
        response_to_id: null,
      },
      {
        id: 17,
        title: "تحلیل پس از اقدام و به‌روزرسانی دکترین",
        description: "بهبود رویه‌های عملیاتی.",
        agency: "ستاد کل نیروهای مسلح",
        completed_at: null,
        status: "published",
        response_to_id: null,
      },
    ],
  },
];

const DEMO_STATS: TimelineStats = {
  total_days: DEMO_DAYS.length,
  total_enemy_actions: DEMO_DAYS.reduce((s, d) => s + d.enemy_actions_count, 0),
  total_government_actions: DEMO_DAYS.reduce(
    (s, d) => s + d.government_actions_count,
    0,
  ),
  response_ratio: 88.2,
};

type HomeClientProps = {
  days?: CalendarDay[];
  maxScore?: number;
  stats?: TimelineStats;
  usingFallback?: boolean;
};

export function HomeClient({
  days = DEMO_DAYS,
  maxScore = 11,
  stats = DEMO_STATS,
  usingFallback = false,
}: HomeClientProps) {
  return (
    <>
      {usingFallback ? (
        <div className="mb-6 rounded-xl border border-amber-400/30 bg-amber-400/10 px-4 py-3 text-sm text-amber-100">
          API در دسترس نیست — داده‌های نمونه نمایش داده می‌شود. پس از بالا آمدن
          بک‌اند، صفحه را رفرش کنید.
        </div>
      ) : null}
      <TimelineView days={days} maxScore={maxScore} stats={stats} />
    </>
  );
}
