/** Default event form schema when API is unavailable */
export const FALLBACK_FORM_SCHEMA = {
  key: "event_create",
  name: "ثبت رویداد",
  is_active: true,
  fields: [
    {
      key: "eventType",
      label: "نوع رویداد",
      type: "select",
      options: [
        { value: "enemy", label: "اقدام دشمن" },
        { value: "government", label: "اقدام دولت" },
      ],
      required: true,
      sort_order: 0,
      section: "main",
      is_system: true,
      is_active: true,
    },
    {
      key: "title",
      label: "عنوان",
      type: "text",
      options: null,
      required: true,
      sort_order: 1,
      section: "main",
      is_system: true,
      is_active: true,
    },
    {
      key: "summary",
      label: "خلاصه",
      type: "textarea",
      options: null,
      required: false,
      sort_order: 2,
      section: "main",
      is_system: true,
      is_active: true,
    },
    {
      key: "date",
      label: "تاریخ",
      type: "date",
      options: null,
      required: true,
      sort_order: 3,
      section: "main",
      is_system: true,
      is_active: true,
    },
    {
      key: "severity",
      label: "شدت",
      type: "select",
      options: [
        { value: "low", label: "کم" },
        { value: "medium", label: "متوسط" },
        { value: "high", label: "بالا" },
        { value: "critical", label: "بحرانی" },
      ],
      required: true,
      sort_order: 4,
      section: "main",
      is_system: true,
      is_active: true,
    },
    {
      key: "description",
      label: "توضیحات",
      type: "textarea",
      options: null,
      required: false,
      sort_order: 5,
      section: "details",
      is_system: false,
      is_active: true,
    },
    {
      key: "location",
      label: "مکان",
      type: "text",
      options: null,
      required: false,
      sort_order: 6,
      section: "details",
      is_system: false,
      is_active: true,
    },
    {
      key: "source",
      label: "منبع",
      type: "text",
      options: null,
      required: false,
      sort_order: 7,
      section: "details",
      is_system: false,
      is_active: true,
    },
  ],
} as const;
